[Build]
BuildSources=kbuild-config:kernel/lkp
BuildSources=.:kernel/lkp/ouichefs
Environment=CONFIG=kernel/lkp/config

[Runtime]
RuntimeBuildSources=yes
RuntimeTrees=homedir:/root

[Content]
Packages=
    bear  # for compile_commands.json of mkfs
    drgn  # for debugging the kernel
